### ISSUE TITLE
The "diff_rescale_mask" method does not work anymore

### ISSUE THREAD

**Issue by someonelike-u** [Ichunjo/vardefunc#16]
Hello,

I think this method does not work anymore since you turned this repository into a python package:
https://github.com/Ichunjo/vardefunc/blob/master/vardefunc/mask.py#L516

When I use this method to preview it in vsedit, the screen is full blank.

Best regards.

**Comment by Ichunjo** [comment]
Hello, can you post your code? I did use it since weeks and it works fine

**Comment by someonelike-u** [comment]
Sure, this is a snippet of my code:

```python
import fvsfunc
import vardefunc
import vsutil

video = core.lsmas.LWLibavSource(source='0001.m2ts')
src16 = vsutil.depth(video, 16)

antiAliasing = applyAntiAliasingMethod(src16)

credits = vardefunc.drm(src16, 720)
maskCredits = core.std.MaskedMerge(antiAliasing, src16, credits)

final = fvsfunc.rfs(antiAliasing, maskCredits, mappings=f'[...]')
```

**Comment by Ichunjo** [comment]
The issue is you’re passing a 16 bits clip to `vardefunc.drm` while the thr is 55. The default threshold isn’t scaled and it’s not static. That means, you have to specify `vardefunc.drm(src16, 720, thr=55<<8)`

I know it’s not really the more convenient but there are two sides:
* Let the user choose their threshold according to the input clip (Maybe I should precise it in the docstring, or at least make it clearer?)
* Forcing a scaled threshold like 8 bits, 16 bits or float values.

Both have cons and pros. I’m trying to follow Vapoursynth logic, the first side. 
For reference, `std.Binarize` lets the user choose the middle point of range allowed by the format.

**Comment by Ichunjo** [comment]
Suggestions and PR are of course welcome.

**Comment by someonelike-u** [comment]
OK, thank you for the clarification.
I think a little bit improve of the doc would be appreciate to understand globally how the parameters of the method work.
